### ISSUE TITLE
Cookies table values not showing

### ISSUE THREAD

**Issue by pieter-janDB** [elleracompany/craft-cookie-consent#16] opened 2020-02-10 15:02 UTC
Hi,

I just upgraded to Craft CMS 3.4.5 and GDPR Cookie consent 1.2.7..

It seems like the cookies table is no longer functional. Values get saved in the database tables but are not visualized in the Control Panel.

Grz,
Pieter-Jan

**Comment by jellingsen** [comment] 2020-02-10 15:03
Thank you for reporting this. I will look into it.

**Comment by jellingsen** [comment] 2020-02-11 07:40
Hi Pieter-Jan

I can't seem to be able to reproduce. I did find a commit sorting consents based on dateUpdated, and that have changed the order of the consents. Can you find the new consents at the end of the dataset?

**Comment by pieter-janDB** [comment] 2020-02-11 11:24
I think you are looking in the wrong place, it is not the table with consents that is not working but the cookie list table within a group.
So for example: http://mysite.com/craft/cookie-consent/group/default/1

under description I fill in the cookies table.
Press Save -> get notification save successfull
page refreshes and table has no more rows.
Checking the DB it gets saved in the cookie_consent_group.cookies field
They also show up in the front end popup,. just not in the table in Controll panel ( So for example: http://mysite.com/craft/cookie-consent/group/default/1 )

**Comment by jellingsen** [comment] 2020-02-11 11:35
Okey!

I'm able to reproduce now. Thank you.

**Comment by jellingsen** [comment] 2020-02-11 11:52
Hi again Pieter-Jan

Can you update to v1.2.8 and see if that fixes the issue for you?

**Comment by pieter-janDB** [comment] 2020-02-11 12:13
Yes, looking good again,
Thanks!

**Comment by pieter-janDB** [comment] 2020-06-04 14:22
Hi again, this issue has returned in 1.3.1

The 'cookie_consent_group' table shows all my groups with their content but the frontend CP (So for example: http://mysite.com/craft/cookie-consent/group/default/1) shows empty tables again (an empty row for every cookie I had there before). Basically the very same as before.

**Comment by jellingsen** [comment] 2020-06-08 12:52
Reopening this and closing #34 for the history.

**Comment by jellingsen** [comment] 2020-06-08 13:25
I've been downgrading and upgrading between 1.2.x and 1.4.0 now to reproduce. The initial bug was introduced with a craftcms update, and no version below 1.2.8 shows the cookies correctly.

What craftcms version are you currently on? And could you give me the contents of the "cookie" column for one of the cookie groups with issues?

**Comment by pieter-janDB** [comment] 2020-06-09 19:23
plugin v1.4
craft v 3.4.22.1
Colleague thinks it goes wrong when getting the serialised data from the db rows..
https://pastebin.com/embed_iframe/KbcnTr8j

**Comment by jellingsen** [comment] 2020-06-10 07:02
Hi!

Your colleague is almost correct, your data is stored wrong in the database. The JSON object is escaped. [this is how it should look](http://sandbox.onlinephpfunctions.com/code/a8760e91ad8a650adb3b6021daabf0f05b8ed838).

I'm not sure how that's been stored like that. I've never experienced it myself. I debating if I should try to add a function that attempts to fix wrongly stored cookies, but I don't want to introduce new bugs.

Could you manually update all your cookie groups and re-add all the cookies? You can either update each cookies-column in the cookie-group table using the function I provided in the link above, or add them fresh in /admin.

If this issue reappears or other people experience it I will look into it again.

**Comment by pieter-janDB** [comment] 2020-06-18 08:21
Hi again,

Could you try uninstalling the plugin and then add this default cookies object to your Plugin.php file ? https://pastebin.com/RLjEsH4e 
This is the way we do it right now since there is no way to copy over gdpr cookie info from one site to another..
Maybe something breaks because of this.. 
It would be great if we had the option to either export/import the settings from the plugin or something like adding the array to a php config file or uploading a json..

**Comment by jellingsen** [comment] 2020-06-19 05:40
Import/Export function is not a bad suggestion. 
Could also look at making it project.yml compatible. 

Now, I uninstalled the plugin, pasted in your pastebin code - still unable to reproduce.
So is this how you currently experience the bug? You install a fresh v1.4^ version of the plugin with modified DEFAULT_GROUPS, or is this how you installed it in a previous version and have updated since?

**Comment by jellingsen** [comment] 2020-07-17 09:54
Any updates here @pieter-janDB ?

**Comment by jellingsen** [comment] 2020-07-27 09:10
Closing this. Reopen or create a new should this issue resurface again

**Closed by jellingsen** 2020-07-27 09:10 UTC
Labels: bug

**Comment by cole007** [comment] 2022-05-17 11:52
Hi

We are experiencing the same issue on a multi-site build.

Craft 3.7.42
Plugin version 1.6.1

Screenshots:
<img width="1075" alt="Screenshot 2022-05-17 at 12 34 23" src="https://user-images.githubusercontent.com/855195/168804612-781fb4b0-5d37-46d1-a997-537489f2ce71.png">
<img width="1196" alt="Screenshot 2022-05-17 at 12 34 31" src="https://user-images.githubusercontent.com/855195/168804669-805f20ca-a40c-426e-8889-3b844862081e.png">

**Comment by jellingsen** [comment] 2022-05-23 16:56
@cole007 Hi! This almost went unnoticed. Could you make a new issue for this?

Please include:
- Steps to reproduce?
- Is it only one one of the sites?
- Do you still have a site with slug "default"?
