### ISSUE TITLE
Plugin broken after update to 1.3.0

### ISSUE THREAD

**Issue by TomDeSmet** [elleracompany/craft-cookie-consent#25] opened 2020-05-25 07:15 UTC
After updating to 1.3.0 my site is down with the following error:
`Getting unknown property: elleracompany\cookieconsent\records\SiteSettings::cookieName`

I noticed you can now set a custom default name for the cookie-consent, which the error refers too. But when I fill in the name field (which should get a default name btw) I get this error:
`Setting unknown property: elleracompany\cookieconsent\records\SiteSettings::acceptAllButton`

**Comment by jellingsen** [comment] 2020-05-25 07:18
Hi,

So the migration is not applied? If you run `./craft migrate --plugin=cookie-consent` this fixes the issue? 

I will look into this now

**Comment by TomDeSmet** [comment] 2020-05-25 07:27
That fixed it alright. Seems it wasn't done automatically.

**Comment by jellingsen** [comment] 2020-05-25 07:29
Nope, i forgot to update the schema version. I will post an update shortly.

Thank you for reporting it.

**Comment by jellingsen** [comment] 2020-05-25 07:50
This is now merged and tested. v1.3.1 is released.

**Comment by johnwbaxter** [comment] 2020-05-28 14:53
@jellingsen This is still broken for me on version 1.3.1 and I ran the emigrate command but it said no migrations were available.

**Comment by johnwbaxter** [comment] 2020-05-28 17:13
Ah ok, looks like you need to save the settings page for a value to be saved into the new db. Done and working now.

**Comment by jellingsen** [comment] 2020-05-28 18:06
Great that i works now. What was not working before you saved the settings?

**Comment by johnwbaxter** [comment] 2020-05-28 18:22
Same error as op: `After updating to 1.3.0 my site is down with the following error:
Getting unknown property: elleracompany\cookieconsent\records\SiteSettings::cookieName`

**Comment by jellingsen** [comment] 2020-05-28 18:27
Okey, so this is still a bug then. I take it that you could open the settings page (you could not in v1.3.0 before migration) and that the default value is not used for the frontend rendering if not set.

Thank you for helping me identify the issue, I will reopen and revisit this issue.

**Comment by johnwbaxter** [comment] 2020-05-28 18:39
Yeah I could open all the pages just fine. Also, it didn't look like there was any info missing. But I didn't really pay close attention to the front end rendering.

**Comment by TomDeSmet** [comment] 2020-05-29 05:45
I have found that this bug is indeed not completely solved but haven't identified yet when the error appears. The error isn't persistent anymore since the migration but still creeps up sometimes. I'll be sure to add more to this thread whenever it pops up again.

**Comment by jellingsen** [comment] 2020-05-29 07:02
Yeah, this is strange.

Record object properties are defined based on the database table, so this error makes perfect sense when the migration is not applied. 

As for the migrations; both the install migration and the v1.3 migration has default value for `SiteSettings::cookieName` so this should never be null.

I've upgraded and downgraded the plugin now and the only time I'm able to reproduce this error is when i upgrade to v1.3.0 without running the migration (the original bug).

I have, however, had the bug appear on different versions when upgrading with composer (rather than the admin panel), this was solved when i ran `php craft clear-caches/all` in the console. This is probably related to the template caching.

I would like you to please provide me with the following information so that I hopefully can reliably reproduce:
1. Did you upgrade to v1.3.0 first or directly from 1.2.x to v1.3.1?
2. If you had v1.3.0 installed at some point, did you run the migration manually?
3. Are you upgrading with composer or via the admin panel?
4. If composer; have you cleared all caches?

**Comment by johnwbaxter** [comment] 2020-05-29 09:04
@jellingsen 

1) 1.2.x to 1.3.1
2) When it wasn't working, I tried to run the migration via ./craft but it said there were no migrations to apply
3) ./craft update all
4) I hadn't unless that craft command does that as part of it's routine
5) No

Thanks!

**Comment by TomDeSmet** [comment] 2020-06-02 12:48
1. 1.2.x to 1.3.0 to 1.3.1
2. Yes
3. Admin panel
4. N/A
5. Yes

**Comment by jellingsen** [comment] 2020-06-08 11:59
Hmm, you've both done it fairly differently. I cant seem to reproduce.
There is a new migration with v1.4, but I've updated the schema version this time.

I think the schema version missing might have introduced a bug somehow. 

@TomDeSmet - have you had any further occurrences of this bug, and have you been able to isolate it more?

**Comment by TomDeSmet** [comment] 2020-06-08 13:07
No, haven't had any issues anymore lately. A colleague of mine had, but that was on an old database. Once he pulled the latest, the bug hasn't surfaced anynmore.

**Comment by jellingsen** [comment] 2020-07-17 09:50
This issue has become stale, and i've been unable to reproduce. I am (again) closing this issue, if this bug resurfaces please reopen.

**Closed by jellingsen** 2020-07-17 09:50 UTC
Labels: High priority, bug
